DROP TABLE IF EXISTS courses;

CREATE TABLE courses (
    SUBJECT_COURSE_SECTION TEXT,
    COURSE_TITLE TEXT,
    PRIMARY_INSTRUCTOR_NAME TEXT,
    A_PLUS TEXT,
    A TEXT,
    A_MINUS TEXT,
    B_PLUS TEXT,
    B TEXT,
    B_MINUS TEXT,
    C_PLUS TEXT,
    C TEXT,
    C_MINUS TEXT,
    D_PLUS TEXT,
    D TEXT,
    D_MINUS TEXT,
    F TEXT,
    WITHDRAWN TEXT,
    SEMESTER TEXT,
    YEAR TEXT
);